kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cup-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cup-local-storage
  resources:
    requests:
      storage: 10Ki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cup-deployment
  labels:
    app: cup
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1m"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cup
  template:
    metadata:
      labels:
        app: cup
    spec:
      containers:
        - name: cup
          image: markbeep/cup:latest
          imagePullPolicy: Always
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cup-secret
                  key: cup-discord-token
          volumeMounts:
            - mountPath: /app/data
              name: cup-data
          resources:
            limits:
              memory: "512Mi"
              cpu: "150m"
      volumes:
        - name: cup-data
          persistentVolumeClaim:
            claimName: cup-claim
