apiVersion: apps/v1
kind: Deployment
metadata:
  name: cup-deployment
  labels:
    app: cup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cup
  template:
    metadata:
      labels:
        app: cup
    spec:
      containers:
        - name: cup
          image: markbeep/cup
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                name: cup-secret
                key: cup-discord-token
          volumeMounts:
            - mountPath: /app/data
              name: cup-data
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: cup-data
          emptyDir: {}
